services:
  energy-service:
    image: energy-service:latest
    container_name: energy-service
    build:
      context: ./energy-service
      dockerfile: src/main/docker/Dockerfile.jvm
    user: root
    ports:
      - "8080:8080"
    volumes:
      - ./energy-service/src/main/resources/data:/app/data
      - project-logs:/project-logs

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./elk/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.0
    container_name: filebeat
    user: root
    command: ["filebeat", "-e", "--strict.perms=false"]
    volumes:
      - ./elk/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - project-logs:/project-logs
    depends_on:
      - energy-service

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  alert-service:
    image: alert-service:latest
    container_name: alert-service
    build:
      context: ./alert-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8081:8080"
    depends_on:
      - kafka

volumes:
  es-data:
  project-logs: